#!/bin/csh -x
#
#  svc_urls --

set debug	= 'debug=False'
set verb	= 'verbose=False'
set warn	= 'warning=False'
set opts	= "$debug $verb $warn"

datalab svc_urls help			# standard help option
datalab svc_urls -help
datalab svc_urls --help

datalab svc_urls $opts
