#!/bin/csh -x
#
#  whoami --

set debug	= 'debug=False'
set verb	= 'verbose=False'
set warn	= 'warning=False'
set opts	= "$debug $verb $warn"

datalab whoami help			# standard help option
datalab whoami -help
datalab whoami --help

datalab whoami $opts
